koninstagram/config/routes.rb
Rails.application.routes.draw do
  resources :customizes
  resources :appointments

end

koninstagram/app/models/appointment.rb
class Appointment < ActiveRecord::Base
 belongs_to :factory
 belongs_to :user
end

koninstagram/app/models/color.rb
class Color < ActiveRecord::Base
    has_many :customize
end

koninstagram/app/models/customize.rb
class Customize < ActiveRecord::Base
    belongs_to :color
    belongs_to :material
    belongs_to :waku
end

koninstagram/app/models/factory.rb
class Factory < ActiveRecord::Base
 has_many :appointments
end

koninstagram/app/models/material.rb
class Material < ActiveRecord::Base
    has_many :customize
end

koninstagram/app/models/user.rb
class User < ActiveRecord::Base
 has_many :appointments
end

koninstagram/app/models/waku.rb
class Waku < ActiveRecord::Base
    has_many :customize
end

koninstagram/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

koninstagram/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
    @factories = Factory.all
  end

  # GET /appointments/1/edit
  def edit
       @factories = Factory.all
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:factory_id, :appoint_date, :user_id, :customize_id)
    end
end

koninstagram/app/controllers/customizes_controller.rb
class CustomizesController < ApplicationController
  before_action :set_customize, only: [:show, :edit, :update, :destroy]

  # GET /customizes
  # GET /customizes.json
  def index
    @customizes = Customize.all
  end

  # GET /customizes/1
  # GET /customizes/1.json
  def show
  end

  # GET /customizes/new
  def new
    @customize = Customize.new
    @colors = Color.all
    @materials = Material.all
    @wakus = Waku.all
    @customize.user_id = 1
  end

  # GET /customizes/1/edit
  def edit
  end

  # POST /customizes
  # POST /customizes.json
  def create
    @customize = Customize.new(customize_params)

    respond_to do |format|
      if @customize.save
        format.html { redirect_to @customize, notice: 'Customize was successfully created.' }
        format.json { render :show, status: :created, location: @customize }
      else
        format.html { render :new }
        format.json { render json: @customize.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customizes/1
  # PATCH/PUT /customizes/1.json
  def update
    respond_to do |format|
      if @customize.update(customize_params)
        format.html { redirect_to @customize, notice: 'Customize was successfully updated.' }
        format.json { render :show, status: :ok, location: @customize }
      else
        format.html { render :edit }
        format.json { render json: @customize.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customizes/1
  # DELETE /customizes/1.json
  def destroy
    @customize.destroy
    respond_to do |format|
      format.html { redirect_to customizes_url, notice: 'Customize was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customize
      @customize = Customize.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customize_params
      params.require(:customize).permit(:color, :material, :waku, :user_id, :color_id, :material_id, :waku_id)
    end
end

koninstagram/app/helpers/application_helper.rb
module ApplicationHelper
end

koninstagram/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

koninstagram/app/helpers/customizes_helper.rb
module CustomizesHelper
end

koninstagram/app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br>
<br>
	<div class="container">
	  <div class="row">
	  	<div class="col-sm-3">
  <div class="form-group">
    <label for="appointment_factory_id">工房選択</label><br>

    <%= f.collection_select(:factory_id,@factories,:id,:name, {}, {:class => 'form-control'}) %>

  </div>	  		
	  	</div>
	  </div>
	</div>


  
  <div id="calendar"></div>
  
  <div class="actions">
    <%= f.submit "予約確定", :class =>"btn btn-default"%>
  </div>
<% end %>

<script>
 $('#calendar').fullCalendar();
</script>

koninstagram/app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

koninstagram/app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Factory</th>
      <th>Appoint date</th>
      <th>User</th>
      <th>Customize</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.factory_id %></td>
        <td><%= appointment.appoint_date %></td>
        <td><%= appointment.user_id %></td>
        <td><%= appointment.customize_id %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

koninstagram/app/views/appointments/new.html.erb
<h1>予約登録</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

koninstagram/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Factory:</strong>
  <%= @appointment.factory_id %>
</p>

<p>
  <strong>Appoint date:</strong>
  <%= @appointment.appoint_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @appointment.user_id %>
</p>

<p>
  <strong>Customize:</strong>
  <%= @appointment.customize_id %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

koninstagram/app/views/customizes/_form.html.erb
<%= form_for(@customize) do |f| %>
  <% if @customize.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customize.errors.count, "error") %> prohibited this customize from being saved:</h2>

      <ul>
      <% @customize.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <label for="customize_color_id">色</label>
    <%= f.select :color_id, @colors.map{|t| [t.name, t.id]}, {}, {:class => 'form-control'} %>
  </div>

  <div class="form-group">
    <label for="customize_material_id">素材</label>
    <%= f.select :material_id, @materials.map{|t| [t.name, t.id]}, {}, {:class => 'form-control'} %>
  </div>

  <div class="form-group">
    <label for="customize_waku_id">枠</label>
    <%= f.select :waku_id, @wakus.map{|t| [t.name, t.id]}, {}, {:class => 'form-control'} %>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit "完了", :class =>"btn btn-default"%>
  </div>
<% end %>

koninstagram/app/views/customizes/edit.html.erb
<h1>Editing Customize</h1>

<%= render 'form' %>

<%= link_to 'Show', @customize %> |
<%= link_to 'Back', customizes_path %>

koninstagram/app/views/customizes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>婚姻届一覧</h1>

<!-- <table> -->
<table class="table">
  <thead>
    <tr>
      <th>色</th>
      <th>素材</th>
      <th>枠</th>
      <th></th>
      <!-- <th>User</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customizes.each do |customize| %>
      <tr>
        <td><%= customize.color.name %></td>
        <td><%= customize.material.name %></td>
        <td><%= customize.waku.name %></td>
        <td><%= image_tag('washi01.jpg',width:150) %></td>
        <!-- <td><%= customize.user_id %></td> -->
        <td><%= link_to '確認', customize %></td>
<!--         <td><%= link_to 'Edit', edit_customize_path(customize) %></td> -->
        <td><%= link_to '削除', customize, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a href="/customizes/new" class="btn btn-default">婚姻届作成</a>
<!-- <%= link_to '婚姻届作成', new_customize_path %> -->

koninstagram/app/views/customizes/new.html.erb
<!--
  <div class="row">
    <h1>New Customize</h1>
    <div class="col-sm-3 col-md-2 sidebar">
        <%= render 'form' %>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        aaa
    </div>
  </div> -->

    <div class="container-fluid">
      <div class="row row-offcanvas row-offcanvas-left">

        <!--sidebar-->
        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <div data-spy="affix" data-offset-top="45" data-offset-bottom="90">
<!--             <ul class="nav" id="sidebar-nav">
              <li><a href="#">Home</a></li>
              <li><a href="#section1">Section 1</a></li>
              <li><a href="#section2">Section 2</a></li>
              <li><a href="#section3">Section 3</a></li>
              <li><a href="#">Holo Theme</a></li>
            </ul>
 -->
            <%= render 'form' %>
          </div>
        </div><!--/sidebar-->

        <!--/main-->
        <div class="col-xs-12 col-sm-9" data-spy="scroll" data-target="#sidebar-nav">


          <div class="row">
            <div class="mag">
                <!-- <img data-toggle="magnify" src="wash01.jpg" class="img-responsive center-block" alt=""> -->
                <%= image_tag('washi01.jpg', :class => "img-responsive center-block", :data => { :toggle => "magnify"}) %>
            </div>
          </div>

            <div class="clearfix"></div>

        </div><!--/.col-xs-12-->
      </div><!--/.row-->
    </div>



<!-- <%= link_to 'Back', customizes_path %>
 -->

koninstagram/app/views/customizes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @customize.color.name %>
</p>

<p>
  <strong>Material:</strong>
  <%= @customize.material.name %>
</p>

<p>
  <strong>Waku:</strong>
  <%= @customize.waku.name %>
</p>

<p>
  <%= image_tag('washi01.jpg', width:200) %>
<!--   <strong>User:</strong>
  <%= @customize.user_id %> -->
</p>

<%= link_to '婚姻届一覧', customizes_path %> |
<%= link_to '予約', new_appointment_path %>

koninstagram/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Koninstagram</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="/moment.min.js"></script>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="/jquery-ui.custom.min.js"></script>
  <script type="text/javascript" src="/fullcalendar.min.js"></script>
  <script type="text/javascript" src="/ja.js"></script>
  <%= csrf_meta_tags %>

</head>
<body>

    <div class="page-container">
        <!-- top navbar -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
               <button type="button" class="navbar-toggle" data-toggle="offcanvas" data-target=".sidebar-nav">
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
               </button>
               <a class="navbar-brand" href="#">婚姻stagram</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li><%= link_to('婚姻届一覧', customizes_path) %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>User1</a>
                </li>
              </ul>
            </div>
        </nav>
        <%= yield %>
    </div>

</body>
</html>